name: Test on main branch with Gradle

on:
  push:
    branches:
    - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clone sub repos
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        git submodule init
        git submodule update
    - name: Print env
      run: echo $GITHUB_ACTOR
    - name: Build and test with Gradle
      run: ./gradlew test -Dorg.gradle.daemon=false
      env:
        PMOS_APP_ID: ${{ secrets.PMOS_APP_ID }}
        PMOS_APP_SECRET: ${{ secrets.PMOS_APP_SECRET }}
        PMOS_ENDPOINT: https://processi.bottegaio.net
        PMOS_PASSWORD: ${{ secrets.PMOS_PASSWORD }}
        PMOS_USERNAME: test

